### ISSUE TITLE
Could you please provide the data pre-process script?

### ISSUE THREAD

**Issue by Junyi-99** [Lingzhi-WANG/KGAUnlearn#1]
I am a newcomer and I am highly interested in your research work. However, I have encountered several issues while trying to run the code. I find it challenging to understand certain parameters, and **I was wondering if you could provide a parameter completion script**. This would greatly assist me in debugging issues on my own!

Specifically, I have the following concerns:

1. Classification: I am unable to run it directly, and I would appreciate guidance on how to get it up and running.

2. The original `IWSLT De-En` and `PersonaChat` datasets do not appear to be in the `*.src` and `*.tgt` formats. Maybe there are some pre-processing scripts?

3. I would like to understand the purpose of the `forget_file`, `new_file`, and `dev_file` parameters. Could you provide an explanation for each?

Thank you for your attention to this matter. I genuinely appreciate your work and look forward to your guidance.

**Comment by Junyi-99** [comment]
For example, as `README.md` described, execute the classification task will cause:

```bash
Namespace(data='/home/junyi/project/LEDGAR_provision_classification/data/LEDGAR/sec_corpus_2016-2019.jsonl', mode='train-forget', do_train=True, do_test=False, do_unlearn=False, model_path=None, new_model_path=None, forget_model_path=None, save_path='junyi_save.pt', sample_ratio=0.05, file_removals='removals.txt', file_as_new='new.txt', test_metric='f1', test_data='test', seed=3735928559, max_seq_len=128, batch_size=32, max_update=50000, max_epoch=1, inner_step=10, print_loss=500, eval_update=1000, save_update=10000, weight_decay=0.01, learning_rate=2e-05, adam_epsilon=1e-08, warmup_steps=500, max_grad_norm=1.0, retain_loss_ratio=0.1)
Setting seeds to:  3735928559
Traceback (most recent call last):
  File "/home/junyi/project/KGAUnlearn_Noted/classification/run_classification.py", line 471, in <module>
    main()
  File "/home/junyi/project/KGAUnlearn_Noted/classification/run_classification.py", line 276, in main
    don_data = DonData(path=args.data)
  File "/home/junyi/project/KGAUnlearn_Noted/classification/utils.py", line 25, in __init__
    self.don_data = split_corpus(path)
NameError: name 'split_corpus' is not defined
```

**Comment by Junyi-99** [comment]
```bash
Namespace(data='/home/junyi/project/LEDGAR_provision_classification/data/LEDGAR/sec_corpus_2016-2019.jsonl', mode='train-forget', do_train=True, do_test=False, do_unlearn=False, model_path=None, new_model_path=None, forget_model_path=None, save_path='junyi_save.pt', sample_ratio=0.05, file_removals='removals.txt', file_as_new='new.txt', test_metric='f1', test_data='test', seed=3735928559, max_seq_len=128, batch_size=32, max_update=50000, max_epoch=1, inner_step=10, print_loss=500, eval_update=1000, save_update=10000, weight_decay=0.01, learning_rate=2e-05, adam_epsilon=1e-08, warmup_steps=500, max_grad_norm=1.0, retain_loss_ratio=0.1)
Setting seeds to:  3735928559
Traceback (most recent call last):
  File "/home/junyi/project/KGAUnlearn_Noted/classification/run_classification.py", line 471, in <module>
    main()
  File "/home/junyi/project/KGAUnlearn_Noted/classification/run_classification.py", line 276, in main
    don_data = DonData(path=args.data)
  File "/home/junyi/project/KGAUnlearn_Noted/classification/utils.py", line 25, in __init__
    self.don_data = split_corpus(path)
  File "/home/junyi/project/KGAUnlearn_Noted/classification/utils.py", line 178, in split_corpus
    x_train, x_test, y_train, y_test = train_test_split(x, y,
NameError: name 'train_test_split' is not defined
```

**Comment by Junyi-99** [comment]
```python
Model name 'distilbert' was not found in model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad). We assumed 'distilbert' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "/home/junyi/miniconda3/envs/unlearn/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/junyi/miniconda3/envs/unlearn/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/junyi/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/junyi/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/junyi/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/junyi/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/junyi/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/junyi/.vscode-server/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/junyi/project/KGAUnlearn_Noted/classification/run_classification.py", line 471, in <module>
    main()
  File "/home/junyi/project/KGAUnlearn_Noted/classification/run_classification.py", line 280, in main
    config = DistilBertConfig.from_pretrained(model_name, num_labels=len(don_data.all_lbls))
  File "/home/junyi/miniconda3/envs/unlearn/lib/python3.9/site-packages/pytorch_transformers/modeling_utils.py", line 194, in from_pretrained
    raise e
  File "/home/junyi/miniconda3/envs/unlearn/lib/python3.9/site-packages/pytorch_transformers/modeling_utils.py", line 180, in from_pretrained
    resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)
  File "/home/junyi/miniconda3/envs/unlearn/lib/python3.9/site-packages/pytorch_transformers/file_utils.py", line 124, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file distilbert not found
```

**Comment by Junyi-99** [comment]
```python
kga_classification.py: error: the following arguments are required: --mode
```

**Comment by Junyi-99** [comment]
```python
total used time: 93.37158823013306
save model to ./save//ckpt_final.pt
Traceback (most recent call last):
  File "/home/junyi/project/KGAUnlearn_Noted/classification/kga_classification.py", line 339, in <module>
    main()
  File "/home/junyi/project/KGAUnlearn_Noted/classification/kga_classification.py", line 303, in main
    threshs = tune_threshs(probas=dev_res['pred'], truth=dev_res['truth'])
  File "/home/junyi/project/KGAUnlearn_Noted/classification/utils.py", line 337, in tune_threshs
    thresh = max(
  File "/home/junyi/project/KGAUnlearn_Noted/classification/utils.py", line 343, in <lambda>
    key=lambda t: f1_score(y_true=truth[:, i], y_pred=(probas[:, i] > t), pos_label=1, average='binary')
NameError: name 'f1_score' is not defined
```

**Comment by Junyi-99** [comment]
# The Response

```bash
2023/11/07 16:21:16 - WARNING - Model - Using cuda device, n_gpu: 8
2023/11/07 16:21:16 - INFO - Model - Initializing model ...
Traceback (most recent call last):
  File "/home/junyi/miniconda3/envs/unlearn/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/home/junyi/miniconda3/envs/unlearn/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/bart-base/resolve/main/tokenizer_config.json

```

**Comment by SmyfakeCoder** [comment]
First，you should go https://github.com/dtuggener/LEDGAR_provision_classification/ to get the function named 'split_corpus', then you should import sklearn to compute the f1_score.
